# Matrix Operation

A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]

In [1]:
import numpy as np

In [4]:
A = np.array([
    [2, -1],
    [0, 3]
])
B = np.array([
    [1,2],
    [-3,4]
])
C = A+B #Addition
print("Addition of Matrixes A and B")
print(C)
C= A.dot(B) #Dot_product
print("Dot product of Matrixes A and B")
print(C)
print("3A-2B")
C = (3*A)-(2*B)
print(C)




Addition of Matrixes A and B
[[ 3  1]
 [-3  7]]
Dot product of Matrixes A and B
[[ 5  0]
 [-9 12]]
3A-2B
[[ 4 -7]
 [ 6  1]]


#  Determinants and Inverses  

In [13]:
A = np.array([[2, 1, 3], 
              [1, 3, 2], 
              [3, 2, 1]])

det_A = round(np.linalg.det(A))
print(f"Determinant of A: {det_A}")

if det_A != 0:
    print("Matrix A is invertible.")
    A_inv = np.linalg.inv(A)
    print(A_inv)
else:
    print("Matrix A is not invertible.")


Determinant of A: -18
Matrix A is invertible.
[[ 0.05555556 -0.27777778  0.38888889]
 [-0.27777778  0.38888889  0.05555556]
 [ 0.38888889  0.05555556 -0.27777778]]


# Eigenvalues and Eigenvectors  

In [14]:
CC = np.array([[4, 1], 
              [-2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(CC)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 2.]
Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


# 4

used np.linalg.pinv(X.T @ X), which computes the pseudoinverse instead of the standard inverse. this handles if matrix is singular or nearly singular

In [16]:
X = np.array([
    [1, 4, 1.5, 100],
    [1, 6, 2.0, 150]
])
y = np.array([20, 30])
beta = np.linalg.pinv(X.T @ X) @ X.T @ y
car3 = np.array([1, 8, 3.0, 200])
price_car3 = car3 @ beta
print(f"The price of car 3 is: {price_car3:.2f}")

The price of car 3 is: 40.00
